### ISSUE TITLE
Tasks / dataview support✨ 

### ISSUE THREAD

**Issue by feedhopper** [ebullient/obsidian-day-planner-og#15]
I would very much like a dialog inside Day planner that allows to set up queries for Tasks and, if possible, also dataview.

The way I imagine this function is pretty straightforward:

1) I can define a time window that has a name, for example 6:30-7:15 workout
2) underneath this created time window, I can pick what tasks are to be filtered for it
3) the time window would then display the queried tasks in day planner timeline
4) the queried tasks can be ticked off directly inside day planner
5) time windows would also have a button to color them so I can easily see what windows I am in currently

This would make Day planner a complete timeblocking solution. Which would be AWESOME!!!

**Comment by ebullient** [comment]
Day PLanner is .. just a note. with a template. You can add callouts right now, if you want to. I recommend being careful with indenting: 

```
- [ ] 14:00 Do some GH things
    > [!todo] List of things for this block
    > query or embed or .. 
    - Could also just list things.
```

Don't overthink things. This is just a note. Day Planner does no magic other than look for the Day Planner header, and timestamped tags underneath.

As it says in the readme, you're free to sprinkle in any other content you want in-between those lines. There is no great magic going on.
