### ISSUE TITLE
✨ Display links as links, or hide the brackets in the timeline?

### ISSUE THREAD

**Issue by RobColes** [ebullient/obsidian-day-planner-og#150]
### 🔖 Feature description

I'm experimenting with Day Planner OG and so far it is great, but I am including links to notes in the planner tasks and these are rendering as text, i.e. the link Pool renders as Pool in the note, but [[Pool]] in the day planner. It is messier if there is a regular link, please see screenshot.

### ✔️ Solution

Ideally the links would render the same as in preview mode in the note and be clickable. 

### ❓ Alternatives

Second choice would be to just render the text itself, and strip out the brackets, and URL for an external link so the text appears in the timeline the same way it appears in preview mode.
![Day Planner](https://github.com/user-attachments/assets/b9f3af29-1740-445d-8020-da3e27b2fd09)

**Comment by ebullient** [comment]
Interesting. I don't use wikilinks and I must not ever have included links in my daily tasks.. so I never noticed. 

I'll have a look
