### ISSUE TITLE
🐛 Dynamic updating of the timeline appears sporadic

### ISSUE THREAD

**Issue by RobColes** [ebullient/obsidian-day-planner-og#154]
### Input data (markdown source)

Loving using day planner to be more intentional with my time!

### Expected Behavior

When adding entries to the "Day planner" section in a note, that the day planner timeline view would be updated in a reasonable time to reflect the changes.

### Current behaviour

Time entries seem to be added pretty dynamically but the text is incorrect, sometimes reflecting the last entry, or a part of the last entry, or sometimes part of the entry it is bumping down. If I exit Obsidian and go back in, it is correct, and doesn't break during the day, just when entries are being edited.

Screenshot "Means justify the ends" displays this

### Steps to reproduce

I have an automation that builds the day planner from my calendar, but I see the same issue if I use the "Add a template" command frrom the command pallette.

Insert timeline items between the beginning and the end entry for the day planner with the day planner visible. Observe the contents.

I also use "Task collector" to keep my todos etc. clean and this also seems to stuff up the timeline.  See screenshot "Day Planner 2" where task collector has remove some earlier entries, the timeline shows the correct times, but old content.

### Which Operating Systems are you using?

- [ ] Android
- [ ] iPhone/iPad
- [ ] Linux
- [ ] macOS
- [X] Windows

### Obsidian Version

1.7.0

### Tasks Plugin Version

0.5.23

### Checks

- [X] I have tried it in the sandbox vault with only this plugin enabled

### Possible solution

Updating the content dynamically would be ideal.

Failing that, a command we could add a hot key for, to rebuild the timeline from scratch would prevent having to exit and restart Obsidian.
![DayPlanner2](https://github.com/user-attachments/assets/88b64040-8009-4574-be81-e831ce21524b)
![Means justify the ENDS](https://github.com/user-attachments/assets/06e75540-8dd3-451e-9b7a-46aca18ba3b2)

**Comment by ebullient** [comment]
I have a feeling this changed when I tried to update this to use links... I'll have to back that out and think of a different way.

**Comment by RobColes** [comment]
Ahh, sorry!

**Comment by ebullient** [comment]
Not your fault... my bad choice. ;)

**Comment by RobColes** [comment]
It's now converting the [[]] internal links in the original note to internet href links which then don't work correctly, e.g. I entered 
[[Weekly Kanban]] using the Obsidian completion to finish it, which was then updated to:
17:00 <a href="Weekly Kanban.md">Weekly Kanban</a>

This displays OK in the original note but doesn't work as a link, and still looks ugly in the timeline.

I'm happy to help test before a release, since I seem to be the cause of most of the problems :-)


<img width="621" alt="hrefs" src="https://github.com/user-attachments/assets/e3c656a9-fffd-4f13-ac82-91beae7e3737">

**Comment by ebullient** [comment]
All is well. Stupid mistakes keep me humble. :-P

**Comment by RobColes** [comment]
If that were true I'd definitely be the world's humblest person 😁

All looking good now, will continue playing but the original note is unmolested and the display, at least for internal links looks good. It is a much cleaner look than I remember from the James Lynch version.

Many thanks for being so responsive to the changes!
