### ISSUE TITLE
Planner Heading Option✨ 

### ISSUE THREAD

**Issue by JohnnyMudcrab** [ebullient/obsidian-day-planner-og#17]
The original version had an option to set the planner heading. So you had the possibility to set a different heading than "Day Planner" to mark the beginning of the Day Planner. It would be really nice if that feature would be reintroduced in the og version.

**Comment by ebullient** [comment]
Must have dropped that somehow. The commit history between the two repos was merged together (and that really made a mess of tags). I had to go back pretty far and hope I landed in a reasonable place..
