### ISSUE TITLE
✨ Picking an "editor"

### ISSUE THREAD

**Issue by ebullient** [ebullient/obsidian-day-planner-og#5]
The problem: 
If Day Planner is active on several devices and "mark completed tasks" is enabled, there will be a race over which device should mark tasks complete.

Can we choose a single device to make those updates?

Rendering the timeline view and showing status bar indicators are read-only activities. Any device should be able to render those (and push alerts) without conflict.

- Does a device have an identifier if sync is not used (general setting? can't remember)
- There are new (perhaps not fully baked) ways to get notified when plugin config has changed.
- Use a command, "I'm the editor?"
- What is the default?

**Comment by sigrunixia** [comment]
> Does a device have an identifier if sync is not used (general setting? can't remember)

Not outwardly, but there may be a way for a plugin to look for the machines ID (You would know this better than I). 

> There are new (perhaps not fully baked) ways to get notified when plugin config has changed.

Those baked in changes are coming, so working on this now isn't a bad idea. 

> Use a command, "I'm the editor?"

Command or setting. I am not against transferring some of the more static items to plugin settings page. It's a QoL feature.

> What is the default?

Hard.. if daily note is created on device B, but device A is default, what happens?

## My ramblings

These are not necessarily in order or connected.

- Crazy idea. Text Generator plugin has these sub packages. What if the presence of these sub packages on a device indicates it's the default?
- One plugin to write and read data, one separate plugin to read data?
- Settings option of default/not default in plugin settings. If device if plugin is not default, can we have it place such settings in `obsidian/plugins/day-planner-og/no-sync/` and auto add that to the core sync plugin exclusion folders? Wont work for third parties syncing.

**Comment by ebullient** [comment]
Resolved by https://github.com/ebullient/obsidian-day-planner-og/commit/f1e3dae7e8d20fb66bc9bc81695954f1c14551b1 .. which would be obvious if not for the typo. 🤷‍♀️
