### ISSUE TITLE
🐛 Nested task support or not?

### ISSUE THREAD

**Issue by HHMathewChan** [ebullient/obsidian-day-planner-og#92]
**Describe the bug**
The nested task does not shown on the timeline view.

**To Reproduce**
1. create a task as 19:40 Dinner routine 
2. create a nested task under as 19: 45 flexibility exercise

**Expected behavior**
In the time block, the task 19: 45 flexibility exercise would display inside the time block of 19:40 Dinner routine.

**Screenshots**
<img width="1920" alt="image" src="https://github.com/ebullient/obsidian-day-planner-og/assets/105818584/0e302fab-17f6-47f0-bfdb-3866a8ddc000">

**Desktop (please complete the following information):**
 - OS: mac os Sonoma 14.4.1

**Additional context**
The expected behaviour is based on your description: "Nested checklist items or bullets are now also supported to capture sub-tasks of a timed task."

**Comment by ebullient** [comment]
Hmm. I may have dropped that when I forked it and cleaned some other things up. 

A sample note (md) containing the an example to test against, like [these](https://github.com/ebullient/obsidian-day-planner-og/tree/main/tests/fixtures) would help.

**Comment by HHMathewChan** [comment]
> Hmm. I may have dropped that when I forked it and cleaned some other things up.
> 
> I believe it only meant that this wouldn't break the world (See [the original commit](https://github.com/ebullient/obsidian-day-planner-og/commit/b90e59670958c6d6d90b2658897b79eff0a8849e)):
> 
> ```
> - [x] 12:00 Reading
>   - [ ] Article 1
>   - [ ] Article 2
>   - [ ] Article notes review
> ```
> 
> Given the way the time layout works.. your example item (exercise) would not show up as a sub-item anyway -- you would move it to a full item to make a new block.

Good to know this is not my setup problem.
